name: Build the project
on:
  push:
    branches:
    - main
  pull_request:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  vendor:
    name: Download and cache dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go mod download

  validate:
    name: Validate Data
    needs: vendor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go run ./cmd/validate

  lint:
    name: Lint Go Code
    needs: vendor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: golangci/golangci-lint-action@v3

  build:
    name: Build Go Code
    needs: vendor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go build ./cmd/eirclode

  package:
    name: Package into a docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: docker/setup-buildx-action@v2
    - name: Login To Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/voytechnology/eirclode:latest
