name: Validate Data
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  validate:
    name: Validate Data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - run: go run ./cmd/validate
